obj-${CONFIG_GPIO_TEST}	+= gpio-test.o
obj-${CONFIG_GPIO_TEST}	+= gpio-irq-test.o
obj-${CONFIG_GPIO_TEST}	+= gpio-toggle-test.o
obj-${CONFIG_GPIO_TEST}	+= gpio-toggle-api-test.o
obj-${CONFIG_GPIO_TEST}	+= gpio-irq-latency-test.o
obj-${CONFIG_GPIO_TEST}	+= gpio-hw-irq-latency-test.o

