PROGRAMS = fbtest_01 fbtest_02 fbtest_03 fbtest_04 fbtest_05 fbtest_06 fbtest_08 fbfire

all: $(PROGRAMS)

fbtest_01: fbtest_01.o

fbtest_02: fbtest_02.o

fbtest_03: fbtest_03.o

fbtest_04: fbtest_04.o

fbtest_05: fbtest_05.o

fbtest_06: fbtest_06.o

fbtest_08: fbtest_08.o

fbfire: fbfire.o

