const char * gpio_output_function_description[] = {
    "GPIO",
    "RES01",
    "RES02",
    "RES03",
    "SLIC_DATA_OUT",
    "SLIC_PCM_FS SLIC",
    "SLIC_PCM_CLK",
    "SPI_CS_1",
    "SPI_CS_2",
    "SPI_CS_0",
    "SPI_CLK",
    "SPI_MOSI",
    "I2S_CLK",
    "I2S_WS",
    "I2S_SD",
    "I2S_MCK",
    "CLK_OBS0",
    "CLK_OBS1",
    "CLK_OBS2",
    "CLK_OBS3",
    "CLK_OBS04",
    "CLK_OBS5",
    "CLK_OBS6",
    "CLK_OBS7",
    "UART0_SOUT",
    "SPDIF_OUT",
    "LED_ACTN_0",
    "LED_ACTN_1",
    "LED_ACTN_2",
    "LED_ACTN_3",
    "LED_ACTN_4",
    "LED_COLN_0",
    "LED_COLN_1",
    "LED_COLN_2",
    "LED_COLN_3",
    "LED_COLN_4",
    "LED_DUPLEXN_0",
    "LED_DUPLEXN_1",
    "LED_DUPLEXN_2",
    "LED_DUPLEXN_3",
    "LED_DUPLEXN_4",
    "LED_LINK_0",
    "LED_LINK_1",
    "LED_LINK_2",
    "LED_LINK_3",
    "LED_LINK_4",
    "ATT_LED",
    "PWR_LED",
    "TX_FRAME",
    "RX_CLEAR_EXTERNAL",
    "LED_NETWORK_EN",
    "LED_POWER_EN",
    "RES_52",
    "RES_53",
    "RES_54",
    "RES_55",
    "RES_56",
    "RES_57",
    "RES_58",
    "RES_59",
    "RES_60",
    "RES_61",
    "RES_62",
    "RES_63",
    "RES_64",
    "RES_65",
    "RES_66",
    "RES_67",
    "RES_68",
    "RES_69",
    "RES_70",
    "RES_71",
    "WMAC_GLUE_WOW",
    "BT_ANT",
    "RX_CLEAR_EXTENSION",
    "RES_75",
    "RES_76",
    "RES_77",
    "ETH_TX",
    "UART1_TD",
    "UART1_RTS",
    "RES_81",
    "RES_82",
    "RES_83",
    "DDR_DQ_OE",
    "RES_85",
    "RES_86",
    "USB_SUSPEND",
    "RES_88",
    "RES_89",
    "RES_90",
    "RES_91"
};

const char * gpio_input_function_description[] = {
    "SPI_MISO",
    "UART0_SIN",
    "RES0",
    "RES1",
    "I2S0_WS",
    "I2S0_MIC_SD",
    "I2SEXTCLK",
    "I2SEXT_MCLK",
    "ETH_RX_ERR",
    "ETH_RX_COL",
    "ETH_RX_CRS",
    "RES2",
    "RES3",
    "RES4",
    "BOOT_EXT_MDO",
    "BOOT_EXT_MDC",
    "SLIC_DATA_IN",
    "SLIC_PCM_FS_IN",
    "RES5",
    "RES6",
    "RES7",
    "RES8",
    "UART1_RD",
    "UART1_CTS"
};

const char * wr_841n_v8[] = {
    "JP2 pin 9",
    "JP2 pin 3",
    "JP2 pin 5",
    "JP2 pin 7",
    "",
    "",
    "",
    "",
    "",
    "JP1 pin 2",
    "JP1 pin 1",
    "",
    "LAN4 LED",
    "WLAN LED",
    "SYSTEM LED",
    "QSS LED",
    "Switch",
    "Button",
    "WAN LED",
    "LAN1 LED",
    "LAN2 LED",
    "LAN3 LED",
    "",
    ""
};

const char * wr_841n_v9[] = {
    "",
    "",
    "",
    "QSS LED",
    "WAN LED",
    "",
    "",
    "",
    "",
    "JP1 pin 2",
    "JP1 pin 1",
    "LAN4 LED",
    "Reset but",
    "WLAN LED",
    "LAN3 LED",
    "LAN2 LED",
    "LAN1 LED",
    "WIFI but",
    "",
    "",
    "",
    "",
    "",
    ""
};
