#
# Copyright (c) 2013 Qualcomm Atheros, Inc.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
snd-soc-ath79-pcm-objs := ath79-pcm.o ath79-mbox.o
snd-soc-ath79-i2s-objs := ath79-i2s.o ath79-i2s-pll.o dev-audio.o
snd-soc-ath79-codec-objs := ath79-internal-codec.o
# snd-soc-db120-objs := qca-db120.o
# snd-soc-cus227-objs := qca-cus227.o

obj-$(CONFIG_SND_ATH79_SOC) += snd-soc-ath79-pcm.o
obj-$(CONFIG_SND_ATH79_SOC_I2S) += snd-soc-ath79-i2s.o
obj-$(CONFIG_SND_ATH79_SOC_CODEC) += snd-soc-ath79-codec.o
# obj-$(CONFIG_SND_ATH79_SOC_DB120) += snd-soc-db120.o
# obj-$(CONFIG_SND_ATH79_SOC_CUS227) += snd-soc-cus227.o
